[config]
# Model and API Configuration
model="gpt-4o"  # Which LLM model to use.
api-base="http://localhost:11434"  # The API url to use for Ollama or Hugging Face.

# Paths
source-file-path="templated_tests/python_fastapi/app.py"  # Path to the source file.
test-file-path="templated_tests/python_fastapi/test_app.py"  # Path to the input test file.
test-file-output-path=""  # Path to the output test file.
code-coverage-report-path="templated_tests/python_fastapi/coverage.xml"  # Path to the code coverage report file.
report-filepath="test_results.html"  # Path to the output report file.
log-db-path=""  # Path to optional log database.
included-files=[]  # a list of files to include in the coverage. For example, "--included-files library1.c library2.c.

# Test Execution
test-command="pytest --cov=. --cov-report=xml --cov-report=term"  # The command to run tests and generate coverage report.
test-command-dir="templated_tests/python_fastapi"  # The directory to run the test command in.
run-tests-multiple-times=1  # int: Number of times to run the tests generated by Cover Agent.

# Coverage Configuration
coverage-type="cobertura"  # Type of coverage report.
desired-coverage=90  # int: The desired coverage percentage.
strict-coverage="False"  # If set, Cover-Agent will return a non-zero exit code if the desired code coverage is not achieved.
use-report-coverage-feature-flag="False"  # Setting this to True considers the coverage of all the files in the coverage report. This means we consider a test as good if it increases coverage for a different file other than the source file.

# Iteration Control
max-iterations=10  # int: The maximum number of iterations.

# Additional Settings
additional-instructions = ""  # Any additional instructions to be appended at the end of the prompt.
